open Parser

let string_of_token : token -> string = function
  | NUMBER n -> string_of_int n
  | ID s -> s
  | INT -> "int"
  | CONST -> "const"
  | VOID -> "void"
  | IF -> "if"
  | ELSE -> "else"
  | WHILE -> "while"
  | BREAK -> "break"
  | CONTINUE -> "continue"
  | RETURN -> "return"
  | PLUS -> "+"
  | MINUS -> "-"
  | TIMES -> "*"
  | DIVIDE -> "/"
  | MOD -> "%"
  | LT -> "<"
  | GT -> ">"
  | LE -> "<="
  | GE -> ">="
  | EQ -> "=="
  | NE -> "!="
  | AND -> "&&"
  | OR -> "||"
  | NOT -> "!"
  | ASSIGN -> "="
  | LPAREN -> "("
  | RPAREN -> ")"
  | LBRACE -> "{"
  | RBRACE -> "}"
  | COMMA -> ","
  | SEMICOLON -> ";"
  | EOF -> "EOF"
